//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProRecruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public long job_Id { get; set; }
        public string job_title { get; set; }
        public string job_discription { get; set; }
        public double salary { get; set; }
        public long company_id { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
